name: termshark
version: '2.1.1'
summary: A terminal UI for tshark, inspired by Wireshark 
description: |
  A terminal UI for tshark, inspired by Wireshark.

confinement: strict
grade: stable
base: core18

parts:
  termshark:
    plugin: go
    source: https://github.com/gcla/termshark.git
    source-type: git
    build-environment:
      - GO111MODULE: 'on'
    override-pull: |
        echo "Skipping pull stage."
    override-build: |
        mkdir $SNAPCRAFT_PART_INSTALL/bin
        export GOBIN=$SNAPCRAFT_PART_INSTALL/bin
        go get github.com/gcla/termshark/v2/cmd/termshark@b59be9c4e73c5271d93318cb4bd4b162a83ec312
    build-packages:
      - gcc
    stage-packages:
      - tshark

apps:
  termshark:
    command: bin/termshark
    plugs:
      - network
      - network-control
      - ppp
      - bluetooth-control
      - raw-usb
      - home
      - firewall-control
      - removable-media
